export const HOME = {
  emergentLink: "emergent-link",
  page: "home-page",
  title: "home-title",
  kpiStrip: "kpi-strip",
  metricCard: "metric-card",
  taskInbox: "task-inbox",
  taskCard: "task-card",
  nbaCard: "nba-card",
  quickActions: "quick-actions",
  teamSummary: "home-team-summary",
};

export const NAV = {
  sidebar: "app-sidebar",
  navItemPrefix: "nav-item",
  topbar: "app-topbar",
  pageTitle: "page-title",
  notifBell: "topbar-notif-bell",
  profileMenu: "topbar-profile-menu",
  orgSwitcher: "topbar-org-switcher",
  orgSwitcherItem: "org-switcher-item",
};

export const WORK = {
  tasksPage: "tasks-page",
  taskCompleteBtn: "task-complete-button",
  taskSnoozeBtn: "task-snooze-button",
  filterPrefix: "task-filter",
  emptyState: "empty-state",
  loadingState: "loading-state",
  retryButton: "data-table-retry-button",
  // ---------------- Fase 40d — daftar tugas sebagai TABEL PRO + drill-down KPI ----------
  taskTable: "task-table",
  taskRow: "task-row",
  taskSearch: "task-search",
  bucketPrefix: "task-bucket",
  bulkComplete: "task-bulk-complete",
  bulkSnooze: "task-bulk-snooze",
  bulkExport: "task-bulk-export",
  // ---------------- Fase 29 — Work Hub v2 (divisi, jobdesk, bukti kerja) ----------------
  tabPrefix: "workhub-tab",
  scopePrefix: "work-scope",
  divisionSelect: "work-division-select",
  createTaskBtn: "work-create-task",
  createTaskSubmit: "work-create-task-submit",
  taskOpenBtn: "task-open-button",
  taskLinkBtn: "task-link-button",
  taskDetail: "task-detail-sheet",
  taskStartBtn: "task-start-button",
  taskSubmitBtn: "task-submit-button",
  taskBuildOpenBtn: "task-build-open-button",
  taskBuildRedirect: "task-build-redirect",
  taskSubmitNote: "task-submit-note",
  taskSubmitPhotos: "task-proof-photo-input",
  taskVerifyBtn: "task-verify-button",
  taskRejectBtn: "task-reject-button",
  taskRejectReason: "task-reject-reason",
  taskAssignBtn: "task-assign-button",
  taskAssignSelect: "task-assign-select",
  taskAssignSubmit: "task-assign-submit",
  board: "division-board",
  boardMemberRow: "board-member-row",
  boardReviewRow: "board-review-row",
  boardUnassignedRow: "board-unassigned-row",
  boardMetric: "board-metric",
  jobdeskPanel: "jobdesk-panel",
  jobdeskRow: "jobdesk-row",
  jobdeskConfigBtn: "jobdesk-config-button",
  jobdeskRunBtn: "jobdesk-run-button",
  jobdeskSaveBtn: "jobdesk-save-button",
  jobdeskSla: "jobdesk-sla-input",
  jobdeskPriority: "jobdesk-priority-select",
  jobdeskAssigneeRule: "jobdesk-assignee-rule",
  jobdeskAssignee: "jobdesk-assignee-select",
  jobdeskVerify: "jobdesk-verify-select",
  jobdeskActive: "jobdesk-active-toggle",
  kanban: "kanban-board",
  kanbanColumn: "kanban-column",
  report: "division-report",
  reportMetric: "report-metric",
  reportMemberRow: "report-member-row",
  reportEvidence: "report-evidence-item",
  reportPrev: "report-week-prev",
  reportNext: "report-week-next",
  pagination: "pagination",
  pagePrev: "pagination-prev",
  pageNext: "pagination-next",
  pageInfo: "pagination-info",
};

export const ADMIN = {
  usersPage: "admin-users-page",
  usersTable: "admin-users-table",
  permsPage: "admin-permissions-page",
  permsMatrix: "admin-permissions-matrix",
  orgsPage: "admin-orgs-page",
  orgRow: "admin-org-row",
  orgAddBtn: "admin-org-add",
  orgName: "admin-org-name",
  orgOwnerName: "admin-org-owner-name",
  orgOwnerEmail: "admin-org-owner-email",
  orgOwnerPassword: "admin-org-owner-password",
  orgCreateSubmit: "admin-org-create-submit",
  orgSwitchBtn: "admin-org-switch",
  orgStatusToggle: "admin-org-status-toggle",
};

export const NOTIF = {
  page: "notifications-page",
  item: "notification-item",
  markAll: "notif-mark-all-button",
};
